### ISSUE TITLE
Fails to install on Vagrant Windows host

### ISSUE THREAD

**Issue by nschubach** [KyleRoss/modclean#1] opened 2015-04-24 18:19 UTC
vagrant@debian-testing-amd64:~/sync$ sudo npm install modclean
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install" "modclean"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.4
npm ERR! path ../rimraf/bin.js
npm ERR! code EROFS
npm ERR! errno -30

npm ERR! rofs EROFS, symlink '../rimraf/bin.js'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

vagrant@debian-testing-amd64:~/sync$ npm --version
2.8.4
vagrant@debian-testing-amd64:~/sync$ node --version
v0.12.2

**Comment by KyleRoss** [comment] 2015-04-24 18:39
@nschubach This error is related to either the file system being read-only or because the file system does not allow symlinks to be created. If you are running the VM on a linux box (which it seems like you are), you would need to install this module using command prompt within the Windows VM itself as npm on linux creates symlinks for CLI files and Windows doesn't support symlinks.

I'm not completely familiar with Vagrant, so I'm not completely sure how it works, although the error you posted pretty much outlines what the issue is.

Give that a try and let me know.

**Comment by KyleRoss** [comment] 2015-04-28 21:31
I'm going to close this issue for now, if you still need help, feel free to reopen.

**Closed by KyleRoss** 2015-04-28 21:31 UTC
Labels: help wanted
